### PR TITLE
Update contentful client to support environments

### PR DESCRIPTION
**Pull request by michalpaukert**

### CODE REVIEW

**Review by MilosHampl — APPROVED** [review]

**Comment by stefanjudis** [comment]
Thanks @michalpaukert. Could we reflect the change in the readme? :)

**Comment by michalpaukert** [comment]
I have updated README could you after merge release new package?

**Comment by stefanjudis** [comment]
@michalpaukert That looks great. Thank you! 🙇 

I just invited you to the repo to have merge access. [`contentful-userland` follow the idea of open open source](https://github.com/contentful-userland/about). I also don't mind giving you access on npm. :) 

What do you think of that?

**Comment by michalpaukert** [comment]
I think it would be better to create some github action to release new package then add access to npm.

**Comment by stefanjudis** [comment]
Agreed. I'm not sure how to set that up (and as you noticed I'm a little short on time). :)

I invited you to this npm project. :)

**Comment by michalpaukert** [comment]
I created account on npm, could you send invite again?

**Comment by stefanjudis** [comment]
Resent. :)

**Comment by michalpaukert** [comment]
This is really weird, I haven´t received any invite. What should I search for?

**Comment by stefanjudis** [comment]
Hmm... mind sending me an email to stefan.judis@contentful.com? Let's take it off the public and figure that one out. :)

**Comment by michalpaukert** [comment]
Hello Stefan,
I tried to reach you on email 3times without success.
Could you check your spam folder?

**Comment by stefanjudis** [comment]
Whoops. You indeed landed in spam. I'll come to that tmrw then. Sorry about that. :/

**Pull request merged**
